config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    get '/like' => 'posts#like'
  end

  resources :tags

root 'posts#index'

resources :users

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' =>'sessions#destroy'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
  
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

end

app/models/post.rb
class Post < ActiveRecord::Base

  markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML.new(:hard_wrap => true, :escape_html => true), :autolink => true, :space_after_headers => true)
  before_save { |post| post.code = markdown.render(post.code) }

  has_many :assignments, dependent: :destroy
  has_many :tags, through: :assignments
  has_many :likes
  belongs_to :user
  before_save :timestamp

  validates :title, :description, presence: true
  
  validates :url, presence: true, url: true, if: ->(instance) { instance.code.blank? }
  validates :code, presence: true, if: ->(instance) { instance.url.blank? }

  def timestamp
    self.timestamp_field = DateTime.now
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :assignments
  has_many :posts, through: :assignments
  validates :title, uniqueness: true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :likes
  has_many :posts

  validates_presence_of :first_name, :last_name, :username
  validates_uniqueness_of :username


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

  helper_method :current_user


  def admin_user
    if current_user && current_user.admin?
      return true
    else
      return false
    end
  end


  def can_change(post)
    if current_user.monitor? || current_user.admin? || current_user.posts.find_by_id(post.id)
      true
    else
      false
    end
  end

  def logged_in?
    if current_user.nil?
      redirect_to login_path
    end
  end

  helper_method :logged_in?

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :logged_in?

  def index
    @posts = Post.all
    @posts = @posts.order('timestamp_field DESC')
    if params[:most_likes]
      @posts = @posts.sort_by{|post| post.likes.length }.reverse
    end
    if params[:most_recent]
      @posts = @posts.order('timestamp_field DESC')
    end

  end

  def show
    @post = Post.find_by_id(params[:id])
    @tag = Tag.find(params[:id])
    @posts = @tag.posts
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save && params[:tag_titles] != nil
      params[:tag_titles].each do |tag|
         Assignment.create(post_id: @post.id, tag_id: Tag.find(tag).id)
      end
      redirect_to root_path, notice: "Post was successfully created."
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    if can_change(@post)
    else
      redirect_to root_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if can_change(@post)
      if @post.update(post_params) && params[:tag_titles] != nil
        params[:tag_titles].each do |tag|
          if !@post.tags.find_by_title(Tag.find(tag).title)
            Assignment.create(post_id: @post.id, tag_id: Tag.find(tag).id)
          end
        end
        redirect_to root_path, notice: "Post was successfully updated."
      else
        render :edit
      end
    else
      redirect_to root_path
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if can_change(@post)
    @post.destroy
    redirect_to root_path, notice: "Post was successfully destroyed."
    end
  end

  def like
    @post = Post.find(params[:post_id])
    @like = Like.create(post_id: @post.id, user_id: current_user.id)
    redirect_to root_path, notice: "Liked!"
  end

  helper_method :user_liked

  def user_liked(post)
    if current_user
      post.likes.each do |like|
        if like.user_id == current_user.id
          return false
        end
      end
    end
    return true
  end

  private

  def post_params
    params.require(:post).permit(:code, :url, :description, :title)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      log_in @user
      redirect_to root_path, notice: "User was successfully Logged In!"
    else
      flash[:notice] = "Incorrect Login Credentials."
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_path, notice: "User was successfully Signed Out"
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def new
  end

  def create
    @tag = Tag.new(title: params[:title])
    if @tag.save
      redirect_to new_post_path
    else
      redirect_to new_post_path
    end
  end

  def show
    @tag = Tag.find(params[:id])
    @posts = @tag.posts
  end

  private

  def tag_params
    params.require(:tag).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :admin_user, only: [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if !admin_user
      @user.monitor = false
    end
    @user.admin = false
    if current_user && current_user.admin?
      @user.save
        redirect_to users_path
    elsif @user.save
      log_in @user
        redirect_to root_path, notice: "Congratulations, User was successfully created!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id || current_user.admin || current_user.monitor
    else
      redirect_to root_path, notice: "Cannot access resource."
    end
  end

  def update
    @user = User.find(params[:id])
    if !admin_user
      @user.monitor = false
    end
    if @user.id == current_user.id || current_user.admin || current_user.monitor
      if @user.update(user_params)
        if current_user.admin
          redirect_to users_path, notice: "User was successfully updated!"
        else
          redirect_to root_path, notice: "User was successfully updated!"
        end
      else
        render :edit
      end
    else
      redirect_to root_path, notice: "Cannot access resource."
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.id == current_user.id || current_user.admin
      @user.destroy
      if current_user && current_user.admin
      else
        session[:user_id] = nil
      end
      if current_user && current_user.admin
        redirect_to users_path, notice: "User was successfully destroyed!"
      else
        redirect_to login_path, notice: "User was successfully destroyed!"
      end
    else
      redirect_to root_path, notice: "Cannot access resource."
    end
  end

# Might need it later on
  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :password, :password_confirmation, :admin, :monitor)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GHarmony</title>
  <%= favicon_link_tag 'gharmony-favicon-white.jpg' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "vendor/modernizr" %>
</head>

<div class="contain-to-grid sticky">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to 'g-Harmony', root_path %></h1>
      </li>
       <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>


    <section class="top-bar-section">
       <!-- Right Nav Section -->
       <ul class="right">
          <% if current_user %>
            <li><%= link_to current_user.username, edit_user_path(current_user) %></li>
            <li class="active"><%= link_to 'Signout', logout_path %></li>
          <% else %>
            <li class="active"><%= link_to 'Signin', login_path %></li>
            <li><%= link_to 'Signup', signup_path %></li>
          <% end %>
          <% if current_user %>
            <% if current_user.admin %>
              <li><%= link_to 'Users', users_path %></li>
            <% end %>
          <% end %>
       </ul>
     </section>
   </nav>
</div>


  <%= yield %>
  <script src="/js/foundation.min.js"></script>
  <script src="/js/vendor/jquery.js"></script>
  <script src="/js/vendor/fastclick.js"></script>
  <script>
    $(document).foundation();
  </script>
</body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div data-alert class="alert-box">
    There were errors on the page:
      <% @post.errors.full_messages.each do |msg| %>
        <li class="errors"><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>

  <p>Add url or code or both:</p>

  <%= f.label :url %>
  <%= f.text_field :url %>
  <br>
  <%= f.label :code %>
  <%= f.text_area :code %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>

  <p>Select one or more tags:<p>
  <hr>
  <% Tag.all.each_with_index do |tag, i| %>
    <div class="medium-3 columns">
      <%= f.label "#{tag.title}" %>
      <% if @post.tags.find_by_title(tag.title) %>
        <input type="checkbox" checked="checked" name="tag_titles[]" value=<%= tag.id %> />
      <% else %>
        <input type="checkbox" name="tag_titles[]" value=<%= tag.id %> />
      <% end %>
    </div>
  <% end %>

  <a href="#" data-reveal-id="myModal">New Tag</a>

  <hr>
  <%= f.submit class: "button" %>
  <%= link_to 'Back Home', root_path, class: "button alert"%>
<% end %>



<div id="myModal" class="reveal-modal" data-reveal>
  <%= render 'tags/form' %>
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/posts/edit.html.erb
<div class="row">
  <div class="medium-8 medium-offset-2 columns">
    <div class="panel">
      <div class="text-center">
        <h1>Edit Post</h1>
      </div>
      <hr>
      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/posts/index.html.erb
<body>
  <div class="row">
    <div class="medium-3 columns" id="side-nav-blue">
      <ul class="side-nav">
        <li><%= link_to "Most Likes", posts_path(:most_likes => true) %></li>
        <li><%= link_to "Recent Posts", posts_path(:most_recent => true) %></li>
        <hr>
        <% Tag.all.each do |tag| %>
          <li><%= link_to tag.title, post_path(tag.id) %></li>
        <% end %>
      </ul>
    </div>


    <% if notice %>
      <div data-alert class="alert-box">
          <div class="alert-text">
            <%= notice %>
          </div>
      </div>
    <% end %>

  <div class="medium-9 columns">

    <br>
    <br>
    <ul class="button-group">
      <li><%= link_to 'New Post', new_post_path, class: "button small" %></li>
    </ul>
    <hr>
    <% @posts.each do |post| %>
      <ul>

        <ul class="like-list">
        <div class="likes">
          <% if user_liked(post) %>
              <%= link_to '<i class="fi-like size-36"></i>'.html_safe, post_like_path(post) %>
          <% else %>
          <i class="fi-like size-36" id="gray-liked"></i>
          <% end %>
        </div>

        <div class="likeh">
          <h6><%= post.likes.size %></h6>
        </div>

      </ul>
        <div class="head">
          <h4><%= post.title %></h4>
        </div>

        <div class="time">
          - <%= post.timestamp_field.strftime("%d/%m/%y") %>
        </div>

        <div class="posted-by">
          <i class="fi-torso-business size-24"></i>  <%= User.find(post.user_id).username %>
        </div>

        <% if post.url != '' && post.code != '' %>
          <p><a href=<%= post.url %> target="_blank" ><%= post.url %></a><p>
          <div class="titles">Code:</div>
          <div class="panel code"><p><%= Redcarpet::Render::SmartyPants.render(post.code).html_safe %></p></div>
        <% elsif post.url != '' %>
          <p><a href=<%= post.url %> target="_blank" ><%= post.url %></a></p>
        <% else %>
          <div class="titles">Code:</div>
          <div class="panel code"> <p><%= Redcarpet::Render::SmartyPants.render(post.code).html_safe %></p> </div>
        <% end %>
        <div class="titles">Description:</div>
        <div class="panel code"><p><%= simple_format(post.description) %></p></div>
      </ul>

          <div class="tags">

            <ul>
              <div class="titles">Tags:</div>

              <!-- <li class="tag-icon" style="margin: 10px 0 0 0;"><i class="fi-pricetag-multiple size-24"></i></li> -->
              <% post.tags.each do |tag| %>
              <li class="tag"></i><%= tag.title %></li>
            <% end %>
            </ul>
          </div>
          <br>

        <% if @current_user.admin || @current_user.posts.find_by_user_id(post.user_id) || @current_user.monitor %>
          <div class="edit">
            <div class="text-right">
              <div class="button small success">
                <%= link_to 'Edit Post', edit_post_path(post) %>
              </div>
              <div class="button small alert">
                <%= link_to 'Delete Post', post_path(post), method: :delete, data: {confirm: 'Are you sure?'} %>
              </div>
            </div>
          </div>
        <% end %>
      <hr>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="medium-8 medium-offset-2 columns">
    <div class="panel">
      <div class="text-center">
        <h1>New Post</h1>
      </div>

      <hr>

      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/posts/show.html.erb
<body>
  <div class="row">
    <div class="medium-3 columns" id="side-nav-blue">
      <ul class="side-nav">
        <li><%= link_to "Most Likes", posts_path(:most_likes => true) %></li>
        <li><%= link_to "Recent Posts", posts_path(:most_recent => true) %></li>
        <hr>
        <% Tag.all.each do |tag| %>
          <li><%= link_to tag.title, post_path(tag.id) %></li>
        <% end %>
      </ul>
    </div>


    <% if notice %>
      <div data-alert class="alert-box">
          <div class="alert-text">
            <%= notice %>
          </div>
      </div>
    <% end %>

  <div class="medium-9 columns">

    <br>
    <br>
    <ul class="button-group">
      <li><%= link_to 'New Post', new_post_path, class: "button small" %></li>
    </ul>
    <hr>
    <% @posts.each do |post| %>
      <ul>

        <ul class="like-list">
        <div class="likes">
          <% if user_liked(post) %>
              <%= link_to '<i class="fi-like size-36"></i>'.html_safe, post_like_path(post) %>
          <% else %>
          <i class="fi-like size-36" id="gray-liked"></i>
          <% end %>
        </div>

        <div class="likeh">
          <h6><%= post.likes.size %></h6>
        </div>

      </ul>
        <div class="head">
          <h4><%= post.title %></h4>
        </div>

        <div class="time">
          - <%= post.timestamp_field.strftime("%d/%m/%y") %>
        </div>

        <div class="posted-by">
          <i class="fi-torso-business size-24"></i>  <%= User.find(post.user_id).username %>
        </div>

        <% if post.url != '' && post.code != '' %>
          <p><a href=<%= post.url %> target="_blank" ><%= post.url %></a><p>
          <div class="titles">Code:</div>
          <div class="panel code"><p><%= Redcarpet::Render::SmartyPants.render(post.code).html_safe %></p></div>
        <% elsif post.url != '' %>
          <p><a href=<%= post.url %> target="_blank" ><%= post.url %></a></p>
        <% else %>
          <div class="titles">Code:</div>
          <div class="panel code"> <p><%= Redcarpet::Render::SmartyPants.render(post.code).html_safe %></p> </div>
        <% end %>
        <div class="titles">Description:</div>
        <div class="panel code"><p><%= simple_format(post.description) %></p></div>
      </ul>

          <div class="tags">

            <ul>
              <div class="titles">Tags:</div>

              <!-- <li class="tag-icon" style="margin: 10px 0 0 0;"><i class="fi-pricetag-multiple size-24"></i></li> -->
              <% post.tags.each do |tag| %>
              <li class="tag"></i><%= tag.title %></li>
            <% end %>
            </ul>
          </div>
          <br>

        <% if @current_user.admin || @current_user.posts.find_by_user_id(post.user_id) || @current_user.monitor %>
          <div class="edit">
            <div class="text-right">
              <div class="button small success">
                <%= link_to 'Edit Post', edit_post_path(post) %>
              </div>
              <div class="button small alert">
                <%= link_to 'Delete Post', post_path(post), method: :delete, data: {confirm: 'Are you sure?'} %>
              </div>
            </div>
          </div>
        <% end %>
      <hr>
    <% end %>
  </div>
</div>

app/views/tags/_form.html.erb
<h2>New Tag</h2>
<%= form_tag tags_path do %>

  <%= label_tag :title %>
  <%= text_area_tag :title %>

  <%= submit_tag nil, class: "button" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password %>

  <% if current_user %>
      <div>
      <%= f.label :monitor %>
      <%= f.check_box :monitor %>
      </div>
  <% end %>

  <%= f.submit class: "button" %>

<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="medium-8 medium-offset-2 columns">
    <div class="panel">

      <div class="text-center">
        <h1>Edit User</h1>
      </div>

      <div class="button alert">
        <%= link_to 'Delete', user_path(@user), method: :delete, data: {confirm: 'Are you sure?'} %>
      </div>

      <% if @user.errors.any? %>
        <div data-alert class="alert-box">
          There were errors on the page:
            <% @user.errors.full_messages.each do |msg| %>
              <li class="errors"><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <hr>

      <%= render 'form' %>


    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="medium-8 medium-offset-2 columns">
    <div class="head">
      <h1>Users</h1>
    </div>
    <div class="new">
      <%= link_to 'Create New User', new_user_path, class: "button right" %>
    </div>

    <hr>

    <% if notice %>
      <div data-alert class="alert-box">
        <%= notice %>
      </div>
    <% end %>

    <table>
      <thead>
        <tr>
          <th width="200px">User Name</th>
          <th width="200px">First Name</th>
          <th width="200px">Last Name</th>
          <th width="200px">Monitor</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td> <%= link_to user.username, user_path(user) %></td>
          <td> <%= user.first_name %></td>
          <td> <%= user.last_name %></td>
          <td> <%= user.monitor %></td>
          <td> <%= link_to 'Edit', edit_user_path(user) %></td>
          <td> <%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
        <% end %>
      </tbody>

    </table>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="medium-8 medium-offset-2 columns">
    <div class="panel">

      <div class="text-center">
        <h1>Sign up!</h1>
      </div>

      <% if @user.errors.any? %>
        <div data-alert class="alert-box">
          There were errors on the page:
            <% @user.errors.full_messages.each do |msg| %>
              <li class="errors"><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <hr>

      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Welcome Logged in user</h1>